shop3/pddl/pddl.lisp
I made a prior fix to make the tests work, that would prefer a local copy of the validator program (from `jenkins/ext/VAL`).  But I didn't realize that would cause loading to fail if the validator had not been built. This patch fixes that.
=> Fix so loading doesn't fail w/o validator.

jenkins/run-tests.sh, shop3/shop3.asd
Fixed the run-tests.sh script to automatically allocate more memory when Lispworks runs out of stack space.
=> Fix for build on lispworks.

jenkins/run-tests.sh, shop3/common/state-decls.lisp, shop3/io/input.lisp, shop3/package.lisp, shop3/shop3.asd, shop3/tests/pddl-tests.lisp, shop3/tests/theorem-prover-tests.lisp, shop3/theorem-prover/decls.lisp, shop3/theorem-prover/package-thpr.lisp
Previously, QUERY required a STATE object as argument. Now it will
alternatively accept a state description (list of facts), as well, and
make the required STATE object itself.
=> Permit state description argument to QUERY.

shop3/decls.lisp, shop3/docs/manual.texinfo, shop3/io/input.lisp, shop3/shop3.asd, shop3/tests/io-tests.lisp, shop3/tests/pddl-tests.lisp
Note that this is in addition to the previously (and still) existing
identifiers for precondition/task-network pairs.
Also added a lookup table in the `domain` object holding the method.
=> Add optional identifier for method forms.

.github/workflows/ci.yml
Adds a translation of the Travis CI config to a Github Actions config.
Differences:
- Uses `Roswell` instead of `cl-travis` just because there was a example Roswell easily available to start from. I think `Roswell` and `cl-travis` are equivalent for this testing environment. If there is a reason to prefer `cl-travis`, I can update the CI config to use that instead.
- A bug was found in the test result checking condition. When `fiveam` runs a suite, it returns a list of test results instead of a single test result. The Travis config was checking the if the result was a test failure. This check misses failures when a test suite is run since the `fiveam` return value, a list of results, is not equal a test failure object. Fixing this check revealed some tests are currently failing on the …
=> Set up GitHub actions CI.

.travis.yml, README.md
Two tests are currently failing when run by Travis. The failure seems to be due to Travis timing out tests that do not produce output for 10 minutes. The two failing tests are longer running tests. The timeout has been increased to 50 minutes to see if that gives the tests enough time to finish.
Example failing job: https://travis-ci.com/github/shop-planner/shop3/jobs/498842611
Relevant Travis documentation: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
=> Increase timeout of Travis CI tests to 50 minutes

.github/workflows/ci.yml
We were not checking for a clean build (no warnings).
There were some minor bugs in testing the return value from the FiveAM tests.
=> Multiple fixes to GitHub workflow

shop3/docs/Makefile, shop3/docs/manual.texinfo
Needs review followed by merge to master.
=> Documentation revisions from Kostas.

shop3/common/state-utils.lisp, shop3/decls.lisp, shop3/io/input.lisp, shop3/planning-engine/task-reductions.lisp
Add DOMAIN-ITEMS -- cache source form of the items. Makes them easier to transfer to another domain.
Add METHOD-DEFINITION-KEYWORDS -- Replace constant with generic function to allow developers of new domain classes to add new keywords to the set of allowable keywords.
=> A number of extensions I made in the process of doing SHOP-MCTS

shop3/docs/legacy-SHOP2-README.txt, shop3/docs/shop3-manual.texinfo, shop3/explicit-stack-search/explicit-search.lisp, shop3/shop3.lisp
Several documentation fixes.
I kept most of the ones from @ko56 , with the exception of some cases where `@var` was used for lisp variables. I checked the Texinfo manuals and it's quite clear that this is not for programming language variables; only for _meta_-variables.
I also found a place where "conjunct" and "disjunct" were used incorrectly in place of _conjunction_ and _disjunction_ -- this is probably a bug carried over from the original SHOP2 manual.
=> Fixes from Kostas.

shop3/shop3.asd, shop3/tests/plan-tree-tests.lisp
These are for `find-plans` only, not `find-plans-stack`, although they could be extended to work for both.
=> Add tests for plan tree construction.

shop3/decls.lisp, shop3/planning-engine/search.lisp, shop3/shop3.asd, shop3/shop3.lisp, shop3/tests/search-tests.lisp
Previously, :ID-ALL would return redundant sets of plans, repeatedly
storing ones that were generated at shallower depths. Fix this by
checking to ensure that a newly-found plan was not found at a depth
below the current depth increment.
=> Fix bugs in Iterative-Deepening search

shop3/shop3.asd, shop3/tests/io-tests.lisp, shop3/tests/warns-check.lisp
By moving warns-check.lisp into the shop-test-helper component, then adding a depends-on to shop-pddl-tests for that module. The other component which was depending on the warns-check, shop-internal-tests, already depends on the shop-test-helper component.
Addresses #138
=> Add explicit dependency between shop-pddl-tests and warns-check.lisp

.github/workflows/ci.yml
Do *not* recursively checkout git submodules.
Use the "checkout" action to handle the git submodules instead of having an additional stanza in the workflow.
=> Fix submodule checkout.

shop3/pddl/fluents.lisp, shop3/pddl/prover.lisp, shop3/theorem-prover/package-thpr.lisp
The symbols for PDDL fluents were not properly getting initialized, causing the buildapp build on CCL to fail.
=> Fix package bug breaking buildapp build.

shop3/buildapp/buildapp-script
This enables us to be able to make buildapp binaries for both CCL and SBCL.  Currently, the buildapp binary is either based on CCL or SBCL, but can't make binaries for both, so we need to install a CCL buildapp and an SBCL buildapp if we want to build both on the same system, and in this case need a mechanism for choosing which to use.
=> Add BUILDAPP variable to the buildapp-script.

shop3/shop3.asd, shop3/tests/theorem-prover-tests.lisp, shop3/theorem-prover/theorem-prover.lisp
The macro was checking for the value of the DOMAIN keyword argument at
run-time instead of at macroexpansion time, which caused
style-warnings from unreachable code from an IF whose condition was T.
=> Fix expansion of SEEK-SATISFIERS.

jenkins/run-tests.sh
1. Make it possible to selectively run the test scripts.
2. Allocate extra memory for Allegro.
3. Expand the stack with `ulimit` (notably for Allegro).
=> Fixes to the test-running script.

shop3/examples/rovers/strips/domain.lisp, shop3/explicit-stack-search/plan-tree.lisp, shop3/hddl/hddl-plan.lisp, shop3/package.lisp, shop3/shop-version.lisp-expr, shop3/shop3.asd, shop3/tests/hddl-tests.lisp, shop3/tests/new-plan-tree-tests.lisp
Miscellaneous fixes, notably to HDDL format plan generation, needed for plan repair experiments to work.
=> Fixes for plan repair

.github/workflows/shop-app.yml
The docker images from the clfoundation are bit-rotted. Use my own instead. These, alas, are also aging.
=> Fix Docker images for buildapp.

shop3/io/input.lisp, shop3/package.lisp, shop3/pddl/pddl.lisp, shop3/shop-version.lisp-expr, shop3/shop3.asd, shop3/tests/pddl-tests.lisp
This property of PDDL domain definitions was not previously supported by our PDDL parser.
=> Add rudimentary support for PDDL :constants.
